// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://2uhe2wcryfezfah4zkjzwjubse.appsync-api.ap-south-1.amazonaws.com/graphql',
          region: 'ap-south-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-3thdliomavc7tft54khmfdjaz4'
        }
    }
};

export default config;